name: stock_project
version: '1.0'
config-version: 2 

profile: stock_proj_duckdbt 

model-paths: ["models"]
analysis-paths: ["analysis"]
asset-paths: ["assets"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

#to do: setup packages-install-path: directory_path? 
#set up docs-path, log-path?

target-path: "target" #where compiled SQL and outputs go
clean-targets: #folders to delete when 'dbt clean' runs
  - "target"
  - "dbt_packages"
  - "logs"

#learn more about model options:
#materialized (view, table, ephemeral, etc)
models:
  stock_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table