name: stock_project
version: '1.0'
config-version: 2 #what is this?

profile: stock_proj_duckdbt #need to create this profile

model-paths: ["models"]
analysis-paths: ["analysis"]
asset-paths: ["assets"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

#to do: setup packages-install-path: directorypath?

#are target-path and clean-targets necessary for my project?
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

#learn more about model options:
#materialized (view, table, ephemeral, etc)
models:
  stock_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table