version: 2

sources:
  - name: stock_source
    description: raw stock data created from Kaggle CSVs via Python scripts.
    schema: main
    tables:
      - name: raw_stockdata_all
        description: contains all stock rows prior to any transformations.

models:
  - name: stg_kaggle__stockdata
    description: >
      Staging transformations for stock data extracted from kaggle datasets.
      Emphasis on standardizing data formats, naming, and fields.    
    
    columns:
      - name: date
        description: trade date for stock data
        tests:
          - not_null

      - name: stock
        description: stock symbol for the stock
        tests:
          - not_null

      - name: open
        description: stock price at market open for the day 
        tests:
          - not_null

      - name: high
        description: highest price the stock reached on a given date
        tests:
          - not_null

      - name: low
        description: lowest price the stock reached on the given date
        tests:
          - not_null

      - name: close
        description: closing price of the stock on the given date
        tests:
          - not_null

      - name: adj_close
        description: adjusted closing price (accounting splits and dividends)
        tests:
          - not_null

      - name: volume
        description: trading volume of the stock on the given date
        tests:
          - not_null
